project:
  type: website
  output-dir: docs

website:
  title: "RASO"
  navbar:
    left:
      - href: index.qmd
        text: Efni
      - setja_upp.qmd
      - verkefni.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



